const SONGS = [
  // === 日本語/Bands & Groups ===
  { id: 1, title: "Subtitle", artist: "Official髭男dism", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: true },
  { id: 2, title: "SOULSOUP", artist: "Official髭男dism", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 3, title: "Sharon", artist: "Official髭男dism", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 4, title: "みどりの雨避け Official", artist: "Official髭男dism", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 5, title: "イエスタデイ", artist: "Official髭男dism", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 6, title: "TATTOO", artist: "Official髭男dism", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 7, title: "115万キロのフィルム", artist: "Official髭男dism", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: true },
  { id: 8, title: "Cry Baby", artist: "Official髭男dism", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: true },
  { id: 9, title: "宿命", artist: "Official髭男dism", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 10, title: "バッドフォーミー", artist: "Official髭男dism", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 11, title: "Pretender", artist: "Official髭男dism", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: true },
  { id: 12, title: "Shower", artist: "Official髭男dism", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 13, title: "Stand By You", artist: "Official髭男dism", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 14, title: "日常", artist: "Official髭男dism", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 15, title: "Chessboard", artist: "Official髭男dism", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 16, title: "アポトーシス", artist: "Official髭男dism", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 17, title: "Laughter", artist: "Official髭男dism", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 18, title: "I LOVE...", artist: "Official髭男dism", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: true },
  { id: 19, title: "アイドル", artist: "YOASOBI", category: "Band", language: "Japanese", tags: ["Bands & Groups", "Anisong/J-POP"], recommended: true },
  { id: 20, title: "勇者", artist: "YOASOBI", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 21, title: "祝福", artist: "YOASOBI", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 22, title: "群青", artist: "YOASOBI", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: true },
  { id: 23, title: "怪物", artist: "YOASOBI", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 24, title: "夜に駆ける", artist: "YOASOBI", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 25, title: "ラブレター", artist: "YOASOBI", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 26, title: "もう少しだけ", artist: "YOASOBI", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 27, title: "たぶん", artist: "YOASOBI", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 28, title: "好きだ", artist: "YOASOBI", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 29, title: "ハルカ", artist: "YOASOBI", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 30, title: "ツバメ", artist: "YOASOBI", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 31, title: "優しい彗星", artist: "YOASOBI", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 32, title: "春泥棒", artist: "ヨルシカ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: true },
  { id: 33, title: "左右盲", artist: "ヨルシカ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 34, title: "嘘月", artist: "ヨルシカ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 35, title: "ブレーメン", artist: "ヨルシカ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 36, title: "風を食む", artist: "ヨルシカ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 37, title: "都落ち", artist: "ヨルシカ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 38, title: "だから僕は音楽を辞めた", artist: "ヨルシカ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: true },
  { id: 39, title: "斜陽", artist: "ヨルシカ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 40, title: "晴る", artist: "ヨルシカ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 41, title: "老人と海", artist: "ヨルシカ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 42, title: "Mela!", artist: "緑黄色社会", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: true },
  { id: 43, title: "あうん", artist: "緑黄色社会", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 44, title: "Landscape", artist: "緑黄色社会", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 45, title: "White Rabbit", artist: "緑黄色社会", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 46, title: "ミチヲユケ", artist: "緑黄色社会", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 47, title: "たとえたとえ", artist: "緑黄色社会", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 48, title: "ずっとずっとずっと", artist: "緑黄色社会", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 49, title: "これからのこと、それからのこと", artist: "緑黄色社会", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 50, title: "花になって", artist: "緑黄色社会", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 51, title: "スクリーンと横顔", artist: "緑黄色社会", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 52, title: "始まりの歌", artist: "緑黄色社会", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 53, title: "sabotage", artist: "緑黄色社会", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 54, title: "ナイスアイディア！", artist: "緑黄色社会", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 55, title: "ライラック", artist: "Mrs. GREEN APPLE", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: true },
  { id: 56, title: "コロンブス", artist: "Mrs. GREEN APPLE", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 57, title: "ロマンチシズム", artist: "Mrs. GREEN APPLE", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 58, title: "In The Morning", artist: "Mrs. GREEN APPLE", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 59, title: "春愁", artist: "Mrs. GREEN APPLE", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 60, title: "点描の唄", artist: "Mrs. GREEN APPLE,井上苑子", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: true },
  { id: 61, title: "水平線", artist: "back number", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: true },
  { id: 62, title: "黄色", artist: "back number", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 63, title: "ヒロイン", artist: "back number", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 64, title: "冬と春", artist: "back number", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 65, title: "クリスマスソング", artist: "back number", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: true },
  { id: 66, title: "Happy Birthday", artist: "back number", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 67, title: "ハッピーエンド", artist: "back number", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 68, title: "カメレオン", artist: "King Gnu", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 69, title: "BOY", artist: "King Gnu", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 70, title: "硝子窓", artist: "King Gnu", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: true },
  { id: 71, title: "傘", artist: "King Gnu", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 72, title: "白日", artist: "King Gnu", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 73, title: "一途", artist: "King Gnu", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 74, title: "逆夢", artist: "King Gnu", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 75, title: "Ham", artist: "ずっと真夜中でいいのに。", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 76, title: "MILABO", artist: "ずっと真夜中でいいのに。", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 77, title: "残機", artist: "ずっと真夜中でいいのに。", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 78, title: "ハゼ馳せる果てるまで", artist: "ずっと真夜中でいいのに。", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 79, title: "脳裏上のクラッカー", artist: "ずっと真夜中でいいのに。", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 80, title: "勘冴えて悔しいわ", artist: "ずっと真夜中でいいのに。", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 81, title: "TAIDADA", artist: "ずっと真夜中でいいのに。", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 82, title: "お勉強しといてよ", artist: "ずっと真夜中でいいのに。", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 83, title: "ミラーチューン", artist: "ずっと真夜中でいいのに。", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 84, title: "消えてしまいそうです", artist: "ずっと真夜中でいいのに。", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 85, title: "クズリ念", artist: "ずっと真夜中でいいのに。", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 86, title: "シェードの埃は延長", artist: "ずっと真夜中でいいのに。", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 87, title: "微熱魔", artist: "ずっと真夜中でいいのに。", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 88, title: "WATER BLUE NEW WORLD", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 89, title: "WONDERFUL STORIES", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 90, title: "MY舞☆TONIGHT", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 91, title: "MIRACLE WAVE", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 92, title: "キセキヒカル", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 93, title: "Landing action Yeah!!", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 94, title: "HAPPY PARTY TRAIN", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 95, title: "SKY JOURNEY", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 96, title: "少女以上の恋がしたい", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 97, title: "Daydream Warrior", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 98, title: "MIRAI TICKET", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 99, title: "恋になりたいAQUARIUM", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 100, title: "待ってて愛のうた", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 101, title: "君のこころは輝いてるかい?", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: true },
  { id: 102, title: "サンシャインぴっかぴか音頭", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 103, title: "ユメ語るよりユメ歌おう", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 104, title: "smile smile ship Start!", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 105, title: "Jump up HIGH!!", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 106, title: "Hop? Stop? Nonstop!", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 107, title: "僕らの走ってきた道は…", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 108, title: "Thank you, FRIENDS!!", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 109, title: "ホップ・ステップ・ワーイ！", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 110, title: "なんどだって約束！", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 111, title: "BANZAI! digital trippers", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 112, title: "ユメ+ミライ＝無限大", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 113, title: "ジングルベルがとまらない", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 114, title: "聖なる日の祈り", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 115, title: "not ALONE not HITORI", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 116, title: "Pops heartで踊るんだもん!", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 117, title: "Aqours☆HEROES", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 118, title: "Step! ZERO to ONE", artist: "Aqours", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 119, title: "Snow halation", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: true },
  { id: 120, title: "START:DASH!!", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 121, title: "輝夜の城で踊りたい", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 122, title: "僕らは今のなかで", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 123, title: "僕たちはひとつの光", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: true },
  { id: 124, title: "愛してるばんざーい!", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 125, title: "No brand girls", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 126, title: "それは僕たちの奇跡", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 127, title: "夏色えがおで1,2,Jump!", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 128, title: "僕らのLIVE 君とのLIFE", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 129, title: "きっと青春が聞こえる", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 130, title: "SUNNY DAY SONG", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 131, title: "ユメノトビラ", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 132, title: "Angelic Angel", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 133, title: "A song for You! You? You!!", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 134, title: "Mermaid festa vol.1", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 135, title: "KiRa-KiRa Sensation!", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 136, title: "Dancing stars on me!", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 137, title: "だってだって噫無情", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 138, title: "LONELIEST BABY", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 139, title: "LOVELESS WORLD", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 140, title: "SENTIMENTAL StepS", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 141, title: "嵐のなかの恋だから", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 142, title: "Shangri-La Shower", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 143, title: "ENDLESS PARADE", artist: "μ's", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 144, title: "TOKIMEKI Runners", artist: "虹ヶ咲学園スクールアイドル同好会", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 145, title: "Love U my friends", artist: "虹ヶ咲学園スクールアイドル同好会", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 146, title: "Colorful Dreams! Colorful Smiles!", artist: "虹ヶ咲学園スクールアイドル同好会", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 147, title: "夢が僕らの太陽さ", artist: "虹ヶ咲学園スクールアイドル同好会", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 148, title: "繚乱！ビクトリーロード", artist: "虹ヶ咲学園スクールアイドル同好会", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 149, title: "What a Wonderful Dream!!", artist: "Liella!", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 150, title: "水しぶきのサイン", artist: "Liella!", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 151, title: "未来は風のように", artist: "Liella!", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 152, title: "Welcome to 僕らのセカイ", artist: "Liella!", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 153, title: "WE WILL!!", artist: "Liella!", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 154, title: "Starlight Prologue", artist: "Liella!", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 155, title: "私のSymphony", artist: "Liella!", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 156, title: "追いかける夢の先で", artist: "Liella!", category: "Group", language: "Japanese", tags: ["Anime Groups"], recommended: false },
  { id: 157, title: "ギターと孤独と蒼い惑星", artist: "結束バンド", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 158, title: "星座になれたら", artist: "結束バンド", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: true },
  { id: 159, title: "忘れてやらない", artist: "結束バンド", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 160, title: "青春コンプレックス", artist: "結束バンド", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: true },
  { id: 161, title: "ラブソングが歌えない", artist: "結束バンド", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 162, title: "光の中へ", artist: "結束バンド", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 163, title: "青い春と西の空", artist: "結束バンド", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 164, title: "あのバンド", artist: "結束バンド", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 165, title: "小さな海", artist: "結束バンド", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 166, title: "フラッシュバッカー", artist: "結束バンド", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 167, title: "なにが悪い", artist: "結束バンド", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 168, title: "10月無口な君を忘れる", artist: "あたらよ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 169, title: "雪冴ゆる", artist: "あたらよ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 170, title: "噓つき", artist: "あたらよ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 171, title: "眠れない夜を君に", artist: "あたらよ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 172, title: "光れ", artist: "あたらよ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 173, title: "恋するもののあはれ", artist: "あたらよ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 174, title: "少年、風薫る", artist: "あたらよ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 175, title: "夏が来るたび", artist: "あたらよ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 176, title: "青を掬う", artist: "あたらよ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 177, title: "アカネチル", artist: "あたらよ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 178, title: "夏霞", artist: "あたらよ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 179, title: "僕らはそれを愛と呼んだ", artist: "あたらよ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 180, title: "「僕は...」", artist: "あたらよ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 181, title: "名もなき何もかも", artist: "トゲナシトゲアリ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 182, title: "爆ぜて咲く", artist: "トゲナシトゲアリ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 183, title: "極私的極彩色アンサー", artist: "トゲナシトゲアリ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 184, title: "傷つき傷つけ痛くて辛い", artist: "トゲナシトゲアリ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 185, title: "空の箱", artist: "トゲナシトゲアリ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 186, title: "雑踏、僕らの街", artist: "トゲナシトゲアリ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 187, title: "視界の隅 朽ちる音", artist: "トゲナシトゲアリ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 188, title: "運命に賭けたい論理", artist: "トゲナシトゲアリ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 189, title: "誰にもなれない私だから", artist: "トゲナシトゲアリ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },
  { id: 190, title: "声なき魚", artist: "トゲナシトゲアリ", category: "Band", language: "Japanese", tags: ["Bands & Groups"], recommended: false },

  // === 日本語/Solo Artists ===
  { id: 191, title: "残響散歌", artist: "Aimer", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: true },
  { id: 192, title: "カタオモイ", artist: "Aimer", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: true },
  { id: 193, title: "Brave Shine", artist: "Aimer", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: true },
  { id: 194, title: "LAST STARDUST", artist: "Aimer", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 195, title: "花びらたちのマーチ", artist: "Aimer", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 196, title: "茜さす", artist: "Aimer", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 197, title: "糸", artist: "Aimer", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 198, title: "星屑ビーナス", artist: "Aimer", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 199, title: "ONE", artist: "Aimer", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 200, title: "ninelie", artist: "Aimer", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 201, title: "RE:I AM", artist: "Aimer", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 202, title: "紅蓮華", artist: "LiSA", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: true },
  { id: 203, title: "炎", artist: "LiSA", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: true },
  { id: 204, title: "明け星", artist: "LiSA", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 205, title: "シルシ", artist: "LiSA", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 206, title: "crossing field", artist: "LiSA", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: true },
  { id: 207, title: "unlasting", artist: "LiSA", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 208, title: "一番の宝物", artist: "LiSA", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 209, title: "往け", artist: "LiSA", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 210, title: "怪獣の花唄", artist: "Vaundy", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: true },
  { id: 211, title: "Tokimeki", artist: "Vaundy", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 212, title: "花占い", artist: "Vaundy", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 213, title: "世界の秘密", artist: "Vaundy", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 214, title: "灯火", artist: "Vaundy", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 215, title: "そんなbitterな話", artist: "Vaundy", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 216, title: "恋風邪にのせて", artist: "Vaundy", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 217, title: "わけあって", artist: "當山みれい", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 218, title: "願い～あの頃のキミへ～", artist: "當山みれい", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 219, title: "雨の音", artist: "當山みれい", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 220, title: "あなたをやめられない", artist: "當山みれい", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 221, title: "^^", artist: "當山みれい", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 222, title: "いやいいや", artist: "當山みれい", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 223, title: "もしも", artist: "當山みれい", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 224, title: "sayonara", artist: "當山みれい", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 225, title: "ユキコイ", artist: "當山みれい", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 226, title: "Sing My Pleasure", artist: "八木海莉", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 227, title: "Harmony of One's Heart", artist: "八木海莉", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 228, title: "My Code", artist: "八木海莉", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 229, title: "お茶でも飲んで", artist: "八木海莉", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 230, title: "刺激による彼ら", artist: "八木海莉", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 231, title: "Galaxy Anthem", artist: "八木海莉", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 232, title: "ねぇ", artist: "藤田麻衣子", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 233, title: "蛍", artist: "藤田麻衣子", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 234, title: "涙が止まらないのは", artist: "藤田麻衣子", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 235, title: "花火", artist: "藤田麻衣子", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 236, title: "瞬间", artist: "藤田麻衣子", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },
  { id: 237, title: "高鳴る", artist: "藤田麻衣子", category: "Solo", language: "Japanese", tags: ["Solo Artists"], recommended: false },

  // === 日本語/Vocaloid Niconico ===
  { id: 238, title: "人生は最高の暇つぶし", artist: "HoneyWorks", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 239, title: "可愛くなりたい", artist: "HoneyWorks,雨宮天", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: true },
  { id: 240, title: "ファンサ", artist: "HoneyWorks", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 241, title: "東京ウインターセッション", artist: "HoneyWorks", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 242, title: "東京サマーセッション", artist: "HoneyWorks", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 243, title: "センパイ。", artist: "HoneyWorks", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 244, title: "我无法成为凛然少女", artist: "はるまきごはん", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 245, title: "再会", artist: "はるまきごはん", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 246, title: "彗星になれたなら", artist: "はるまきごはん", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 247, title: "ルーザーガール", artist: "ツユ", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 248, title: "過去に囚われている", artist: "ツユ", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 249, title: "少女地獄", artist: "ユリイ・カノン,月詠み", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 250, title: "対象x", artist: "ユリイ・カノン,月詠み", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 251, title: "おどりゃんせ", artist: "ユリイ・カノン,月詠み", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 252, title: "ネクロポリス", artist: "ユリイ・カノン,月詠み", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 253, title: "ヨダカ", artist: "ユリイ・カノン,月詠み", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 254, title: "おじゃま虫", artist: "DECO*27,初音ミク", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: true },
  { id: 255, title: "乙女解剖", artist: "DECO*27,初音ミク", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: true },
  { id: 256, title: "妄想税", artist: "DECO*27", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 257, title: "KING", artist: "Kanaria,GUMI", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: true },
  { id: 258, title: "フォニイ", artist: "可不,ツミキ", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: true },
  { id: 259, title: "キュートなカノジョ", artist: "syudou", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 260, title: "回る空うさぎ", artist: "Orangestar,初音ミク", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: true },
  { id: 261, title: "ツギハギスタッカート", artist: "とあ", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 262, title: "神のまにまに", artist: "れるりり", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: true },
  { id: 263, title: "アイ情劣等生", artist: "かいりきベア", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 264, title: "ルマ", artist: "かいりきベア", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 265, title: "大きな世界", artist: "40mP", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 266, title: "名前のない星", artist: "40mP", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 267, title: "Bad ∞ End ∞ Night系列", artist: "其他", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 268, title: "粛聖!! ロリ神レクイエム", artist: "しぐれうい", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: true },
  { id: 269, title: "夜のうた", artist: "きくお", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 270, title: "罰ゲーム", artist: "96猫", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 271, title: "嘘の火花", artist: "96猫", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 272, title: "ダダダダ天使", artist: "七音阿卡莉", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 273, title: "完全放棄宣言", artist: "七音阿卡莉", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 274, title: "メンタルチェンソー", artist: "P丸様｡", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },
  { id: 275, title: "ちきゅう大爆発", artist: "P丸様｡", category: "Vocaloid", language: "Japanese", tags: ["Vocaloid/Niconico"], recommended: false },

  // === 东方Project (Touhou) ===
  { id: 276, title: "色は匂へど 散りぬるを", artist: "森永真由美,幽閉サテライト", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: true },
  { id: 277, title: "大地に咲く旋律", artist: "幽閉サテライト", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 278, title: "泡沫、哀のまほろば", artist: "幽閉サテライト", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 279, title: "華鳥風月", artist: "幽閉サテライト", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 280, title: "今、誰が為のかがり火へ", artist: "幽閉サテライト", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 281, title: "秘めやかなる背徳", artist: "幽閉サテライト", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 282, title: "濡れた髪に触れられた時", artist: "幽閉サテライト", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 283, title: "穢れなきユーフォリア", artist: "幽閉サテライト", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 284, title: "ゼロへ旅立てるのなら", artist: "幽閉サテライト", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 285, title: "月に叢雲華に風", artist: "幽閉サテライト", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 286, title: "想いが歴史に変わる時", artist: "幽閉サテライト", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 287, title: "炸裂アイロニー", artist: "幽閉サテライト", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 288, title: "カフカなる群青へ", artist: "幽閉サテライト", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 289, title: "花月夜", artist: "Yonder Voice", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 290, title: "決別の旅", artist: "Yonder Voice", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 291, title: "千ノ縁", artist: "Yonder Voice", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 292, title: "残光", artist: "Yonder Voice", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 293, title: "紅き恋歌に染めた古戦場", artist: "Yonder Voice", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 294, title: "雪幻ティルナノーグ", artist: "Yonder Voice", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 295, title: "果てなき風の軌跡さえ", artist: "少女フラクタル", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 296, title: "私という好奇心", artist: "少女フラクタル", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 297, title: "うたかた", artist: "豚乙女", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 298, title: "幻想のサテライト", artist: "豚乙女", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 299, title: "魔理沙に大変な役でハコにされました", artist: "IOSYS", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 300, title: "Bad Apple!!", artist: "のみこ", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: true },
  { id: 301, title: "Help me, ERINNNNNN!!", artist: "Beatmario", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 302, title: "鳥よ", artist: "凋叶棕", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 303, title: "絶対的一方通行", artist: "其他同人", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 304, title: "ヒカリ", artist: "めらみぽっぷ", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 305, title: "rebellion", artist: "3L", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 306, title: "童心流転・啓夢", artist: "涼月真宵", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },
  { id: 307, title: "タイムパラドックス", artist: "森羅万象", category: "Touhou", language: "Japanese", tags: ["Touhou"], recommended: false },

  // === Anisong / J-POP ===
  { id: 308, title: "踊", artist: "Ado", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: true },
  { id: 309, title: "アタシは問題作", artist: "Ado", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 310, title: "阿修羅ちゃん", artist: "Ado", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 311, title: "ギラギラ", artist: "Ado", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 312, title: "新時代", artist: "Ado", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 313, title: "第六感", artist: "Reol", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: true },
  { id: 314, title: "ミラージュ", artist: "Reol", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 315, title: "No title", artist: "Reol", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 316, title: "色彩", artist: "りりあ。", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 317, title: "私じゃなかったんだね", artist: "りりあ。", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 318, title: "じゃあね、またね。", artist: "りりあ。", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 319, title: "失恋ソング沢山聴いて...", artist: "りりあ。", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 320, title: "夏風に溶ける", artist: "りりあ。", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 321, title: "ロマンスの約束", artist: "幾田りら", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 322, title: "Midnight Talk", artist: "幾田りら", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 323, title: "おもかげ", artist: "幾田りら", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 324, title: "蒲公英", artist: "幾田りら", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 325, title: "ドライフラワー", artist: "優里", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: true },
  { id: 326, title: "ベテルギウス", artist: "優里", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: true },
  { id: 327, title: "まつり", artist: "藤井風", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 328, title: "花", artist: "藤井風", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 329, title: "満ちてゆく", artist: "藤井風", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 330, title: "きらり", artist: "藤井風", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 331, title: "Hello Song", artist: "星野源", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 332, title: "Week End", artist: "星野源", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 333, title: "恋", artist: "星野源", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 334, title: "ブルーバード", artist: "いきものがかり", category: "Band", language: "Japanese", tags: ["Anisong/J-POP"], recommended: true },
  { id: 335, title: "YELL", artist: "いきものがかり", category: "Band", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 336, title: "心の花を咲かせよう", artist: "いきものがかり", category: "Band", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 337, title: "ありがとう", artist: "いきものがかり", category: "Band", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 338, title: "Avid", artist: "SawanoHiroyuki[nZk]", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 339, title: "sh0ut", artist: "SawanoHiroyuki[nZk]", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 340, title: "gravityWall", artist: "SawanoHiroyuki[nZk]", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 341, title: "Cage", artist: "SawanoHiroyuki[nZk]", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 342, title: "Hands Up to the Sky", artist: "SawanoHiroyuki[nZk]", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 343, title: "Möbius", artist: "SawanoHiroyuki[nZk]", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 344, title: "Unti-L", artist: "SawanoHiroyuki[nZk]", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 345, title: "ひらひら ひらら", artist: "ClariS", category: "Group", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 346, title: "CLICK", artist: "ClariS", category: "Group", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 347, title: "ヒトリゴト", artist: "ClariS", category: "Group", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 348, title: "コネクト", artist: "ClariS", category: "Group", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 349, title: "Overfly", artist: "春奈るな", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 350, title: "Startear", artist: "春奈るな", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 351, title: "空は高く風は歌う", artist: "春奈るな", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 352, title: "君色シグナル", artist: "春奈るな", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 353, title: "INNOCENCE", artist: "藍井エイル", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 354, title: "IGNITE", artist: "藍井エイル", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 355, title: "I will...", artist: "藍井エイル", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 356, title: "Sincerely", artist: "TRUE", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 357, title: "Storyteller", artist: "TRUE", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 358, title: "恋はヒラひらり", artist: "Goose house", category: "Group", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 359, title: "光るなら", artist: "Goose house", category: "Group", language: "Japanese", tags: ["Anisong/J-POP"], recommended: true },
  { id: 360, title: "Euterpe", artist: "EGOIST", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 361, title: "Only My Railgun", artist: "fripSide", category: "Band", language: "Japanese", tags: ["Anisong/J-POP"], recommended: true },
  { id: 362, title: "満天", artist: "Kalafina", category: "Group", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 363, title: "音楽", artist: "Kalafina", category: "Group", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 364, title: "うみねこのなく頃に", artist: "志方あきこ", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 365, title: "片翼の鳥", artist: "志方あきこ", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 366, title: "白夢の繭", artist: "志方あきこ", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 367, title: "打上花火", artist: "Daoko,米津玄師", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: true },
  { id: 368, title: "Lemon", artist: "米津玄師", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: true },
  { id: 369, title: "感電", artist: "米津玄師", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: true },
  { id: 370, title: "廻廻奇譚", artist: "Eve", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: true },
  { id: 371, title: "幾億光年", artist: "Omoinotake", category: "Band", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 372, title: "We Are", artist: "ONE OK ROCK", category: "Band", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 373, title: "No.1", artist: "西野カナ", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 374, title: "Bitter", artist: "ビッケブランカ", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 375, title: "ヨワネハキ", artist: "MAISONdes", category: "Group", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 376, title: "LOVE2000", artist: "HITOMI", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 377, title: "カワキヲアメク", artist: "美波", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: true },
  { id: 378, title: "面影", artist: "Novelbright", category: "Band", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 379, title: "小さな恋のうた", artist: "新垣结衣", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: true },
  { id: 380, title: "青春のアーカイブ", artist: "碧蓝档案", category: "Group", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 381, title: "不可思議のカルテ", artist: "青春猪头少年", category: "Group", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 382, title: "動く、動く", artist: "少女终末旅行", category: "Group", language: "Japanese", tags: ["Anisong/J-POP"], recommended: false },
  { id: 383, title: "甲賀忍法帖", artist: "陰陽座", category: "Band", language: "Japanese", tags: ["Anisong/J-POP"], recommended: true },
  { id: 384, title: "星の在り処", artist: "雪幽游,Falcom", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: true },
  
  // === 中文 ===
  { id: 385, title: "像我这样的人", artist: "毛不易", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 386, title: "消愁", artist: "毛不易", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 387, title: "借", artist: "毛不易", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 388, title: "给你给我", artist: "毛不易", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 389, title: "平凡的一天", artist: "毛不易", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 390, title: "不染", artist: "毛不易", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 391, title: "无问", artist: "毛不易", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 392, title: "入海", artist: "毛不易", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 393, title: "一程山路", artist: "毛不易", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 394, title: "如果有一天我变得很有钱", artist: "毛不易", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 395, title: "感觉自己是巨星", artist: "毛不易", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 396, title: "芬芳一生", artist: "毛不易", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 397, title: "若有缘由", artist: "毛不易", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 398, title: "水乡", artist: "毛不易", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 399, title: "光年之外", artist: "G.E.M.邓紫棋", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 400, title: "泡沫", artist: "G.E.M.邓紫棋", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 401, title: "多远都要在一起", artist: "G.E.M.邓紫棋", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 402, title: "你不是真正的快乐 (Live)", artist: "G.E.M.邓紫棋", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 403, title: "差不多姑娘", artist: "G.E.M.邓紫棋", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 404, title: "超能力", artist: "G.E.M.邓紫棋", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 405, title: "一重加害", artist: "Vsinger", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 406, title: "四重罪孽", artist: "Vsinger", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 407, title: "七重痼病", artist: "Vsinger", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 408, title: "九九八十一", artist: "Vsinger", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 409, title: "万古生香", artist: "Vsinger", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 410, title: "霜雪千年", artist: "Vsinger", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 411, title: "勾指起誓", artist: "Vsinger", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 412, title: "阴阳先生", artist: "Vsinger", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 413, title: "权御天下", artist: "Vsinger", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 414, title: "我的悲伤是水做的", artist: "Vsinger", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 415, title: "I Love U", artist: "Vsinger", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 416, title: "一梦千宵", artist: "Vsinger", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 417, title: "世末歌者", artist: "Vsinger", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 418, title: "普通disco", artist: "Vsinger", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 419, title: "达拉崩吧", artist: "Vsinger,ilem", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 420, title: "匆匆那年", artist: "王菲", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 421, title: "因为爱情", artist: "王菲", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 422, title: "红豆", artist: "王菲", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 423, title: "白痴", artist: "王菲", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 424, title: "传奇", artist: "王菲", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 425, title: "爱情转移", artist: "陈奕迅", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 426, title: "浮夸", artist: "陈奕迅", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 427, title: "没离开过", artist: "林志炫", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 428, title: "烟花易冷", artist: "林志炫", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 429, title: "单身情歌", artist: "林志炫", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 430, title: "宁夏", artist: "梁静茹", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 431, title: "可惜不是你", artist: "梁静茹", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 432, title: "彩虹的微笑", artist: "王心凌", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 433, title: "爱你", artist: "王心凌", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 434, title: "我怀念的", artist: "孙燕姿", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 435, title: "咕叽咕叽", artist: "孙燕姿", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 436, title: "大鱼", artist: "周深", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 437, title: "听海", artist: "张惠妹", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 438, title: "生僻字", artist: "其他华语歌手", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 439, title: "蜜雪冰城主题曲", artist: "其他华语歌手", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 440, title: "野狼disco", artist: "其他华语歌手", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 441, title: "孤单北半球", artist: "其他华语歌手", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 442, title: "红色高跟鞋", artist: "其他华语歌手", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 443, title: "讲真的", artist: "其他华语歌手", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 444, title: "戒烟", artist: "李荣浩", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 445, title: "修炼爱情", artist: "林俊杰", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 446, title: "阴天", artist: "莫文蔚", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 447, title: "笼", artist: "张碧晨", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 448, title: "甜蜜蜜", artist: "邓丽君", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 449, title: "赤伶", artist: "李玉刚", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 450, title: "错位时空", artist: "其他华语歌手", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },
  { id: 451, title: "阿拉斯加海湾", artist: "其他华语歌手", category: "Chinese", language: "Chinese", tags: ["Chinese"], recommended: false },

  // === Other Languages ===
  { id: 452, title: "Let It Go", artist: "Frozen", category: "Western", language: "English", tags: ["Western"], recommended: false },
  { id: 453, title: "Do You Want to Build a Snowman?", artist: "Frozen", category: "Western", language: "English", tags: ["Western"], recommended: false },
  { id: 454, title: "For the First Time in Forever", artist: "Frozen", category: "Western", language: "English", tags: ["Western"], recommended: false },
  { id: 455, title: "Love Is an Open Door", artist: "Frozen", category: "Western", language: "English", tags: ["Western"], recommended: false },
  { id: 456, title: "Into the Unknown", artist: "Frozen", category: "Western", language: "English", tags: ["Western"], recommended: false },
  { id: 457, title: "Castle On A Cloud", artist: "Les Misérables Cast", category: "Western", language: "English", tags: ["Western"], recommended: false },
  { id: 458, title: "Stars", artist: "Les Misérables Cast", category: "Western", language: "English", tags: ["Western"], recommended: false },
  { id: 459, title: "One Day More", artist: "Les Misérables Cast", category: "Western", language: "English", tags: ["Western"], recommended: false },
  { id: 460, title: "On My Own", artist: "Les Misérables Cast", category: "Western", language: "English", tags: ["Western"], recommended: false },
  { id: 461, title: "Penser l'impossible", artist: "Mozart l'Opéra Rock Cast", category: "Western", language: "French", tags: ["Western"], recommended: false },
  { id: 462, title: "Vivre à en crever", artist: "Mozart l'Opéra Rock Cast", category: "Western", language: "French", tags: ["Western"], recommended: false },
  { id: 463, title: "La gloire à mes genoux", artist: "Mozart l'Opéra Rock Cast", category: "Western", language: "French", tags: ["Western"], recommended: false },
  { id: 464, title: "History", artist: "One Direction", category: "Western", language: "English", tags: ["Western"], recommended: false },
  { id: 465, title: "Look At Me Now", artist: "Charlie Puth", category: "Western", language: "English", tags: ["Western"], recommended: false },
  { id: 466, title: "Say So", artist: "Doja Cat", category: "Western", language: "English", tags: ["Western"], recommended: false },
  { id: 467, title: "Try Everything", artist: "Shakira", category: "Western", language: "English", tags: ["Western"], recommended: false },
  { id: 468, title: "Coincidance", artist: "Handsome Dancer", category: "Western", language: "English", tags: ["Western"], recommended: false },
  { id: 469, title: "The Feels", artist: "TWICE", category: "Western", language: "English", tags: ["Western"], recommended: false },
  
  // === 补充 おすすめ 中的其他独立项 ===
  { id: 470, title: "ちゅ、多様性。", artist: "ano", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: true },
  { id: 471, title: "悪魔の子", artist: "ヒグチアイ", category: "Solo", language: "Japanese", tags: ["Anisong/J-POP"], recommended: true }
];

const FILTER_OPTIONS = {
  categories: ["Band", "Solo", "Group", "Vocaloid", "Touhou", "Chinese", "Western"],
  languages: ["Japanese", "Chinese", "English", "French"],
  tags: ["Bands & Groups", "Solo Artists", "Anime Groups", "Vocaloid/Niconico", "Touhou", "Anisong/J-POP", "Chinese", "Western"]
};